//go:build unix

package cli

import (
	"context"
	"strings"
	"testing"

	"github.com/safegrd/cli/pkg/config"
)

// A credential from a command was documented, generated by the console and
// recommended on the security page, and nothing ever ran it: a mailbox
// configured the way we told people to failed with "credentials unresolved".
func TestCredentialCommandSuppliesTheSecret(t *testing.T) {
	ctx := context.Background()
	t.Setenv("SAFEGRD_EMAIL_PASSWORD", "stale-from-env")

	s := &config.SurfaceConfig{ID: "mail", Credential: fromCommand(`printf 'hunter2\n'`)}
	if got, err := surfaceEmailPassword(ctx, s); err != nil || got != "hunter2" {
		t.Fatalf("password = %q, %v; want hunter2 from the command, ahead of the environment", got, err)
	}

	// A command that fails is the answer; the leftover variable is not used.
	s.Credential.Run = `echo "not signed in" >&2; exit 1`
	_, err := surfaceEmailPassword(ctx, s)
	if err == nil || !strings.Contains(err.Error(), "not signed in") || !strings.Contains(err.Error(), "surface mail") {
		t.Fatalf("a failing command must fail the surface and say why: %v", err)
	}

	// Stdout is the secret, so it never reaches an error message.
	s.Credential.Run = `echo leaked-secret; exit 3`
	if _, err := surfaceEmailPassword(ctx, s); err == nil || strings.Contains(err.Error(), "leaked-secret") {
		t.Fatalf("stdout leaked into the error: %v", err)
	}

	s.Credential.Run = `true`
	if _, err := surfaceEmailPassword(ctx, s); err == nil || !strings.Contains(err.Error(), "printed nothing") {
		t.Fatalf("an empty secret must be refused: %v", err)
	}

	// A surface that names no credential uses the default variable.
	s.Credential = nil
	if got, _ := surfaceEmailPassword(ctx, s); got != "stale-from-env" {
		t.Fatalf("fallback = %q", got)
	}
}

func fromCommand(run string) *config.CredentialConfig {
	return &config.CredentialConfig{From: config.CredentialFromCommand, Run: run}
}

func TestCredentialCommandSuppliesADatabaseURL(t *testing.T) {
	ctx := context.Background()
	c := &config.CLIConfig{DatabaseURL: "postgres://host-default/app"}
	s := &config.SurfaceConfig{ID: "db", Credential: fromCommand(`echo postgres://from-vault/app`)}
	if got, err := resolveSurfaceDatabaseURL(ctx, c, s); err != nil || got != "postgres://from-vault/app" {
		t.Fatalf("got %q, %v", got, err)
	}
	// A database_url as well is two origins, and refused.
	s.DatabaseURL = "postgres://explicit/app"
	if _, err := resolveSurfaceDatabaseURL(ctx, c, s); err == nil || !strings.Contains(err.Error(), "one origin") {
		t.Fatalf("a command and a database_url: %v", err)
	}
	// A sandbox check that cannot resolve the source refuses the drill.
	s.DatabaseURL = ""
	s.Credential.Run = "exit 1"
	s.Type = "postgres"
	s.Drill = &config.DrillConfig{SandboxURL: "postgres://sandbox/scratch"}
	if _, err := surfaceSandboxURL(ctx, c, s); err == nil || !strings.Contains(err.Error(), "refusing to drill") {
		t.Fatalf("an unresolvable source must refuse the drill: %v", err)
	}
}

// doctor finds a credential that will not resolve before the daemon does.
func TestDoctorResolvesSurfaceCredentials(t *testing.T) {
	t.Setenv("SAFEGRD_EMAIL_PASSWORD", "")
	c := &config.CLIConfig{Surfaces: []config.SurfaceConfig{
		{ID: "ok", Type: "email", Username: "a@b", Credential: fromCommand("echo pw")},
		{ID: "locked", Type: "email", Username: "a@b", Credential: fromCommand("echo 'vault sealed' >&2; exit 2")},
		{ID: "unset", Type: "email", Username: "a@b", Credential: &config.CredentialConfig{From: "env", Name: "SAFEGRD_TEST_NOT_SET"}},
		{ID: "tree", Type: "files", Roots: []string{"/"}},
	}}
	got := map[string]CheckResult{}
	for _, r := range surfaceCredentialChecks(c) {
		got[r.Name] = r
	}
	if r := got["Surface ok credentials"]; r.Status != "PASS" || !strings.Contains(r.Message, "credential.run") {
		t.Errorf("ok: %+v", r)
	}
	if r := got["Surface locked credentials"]; r.Status != "FAIL" || !strings.Contains(r.Message, "vault sealed") {
		t.Errorf("locked: %+v", r)
	}
	if r := got["Surface unset credentials"]; r.Status != "FAIL" {
		t.Errorf("unset: %+v", r)
	}
	if _, ok := got["Surface tree credentials"]; ok {
		t.Error("a files surface has no credential to check")
	}
}
