#!/bin/sh
# Print the Homebrew formula for one release, from its checksums.txt.
#
#   scripts/homebrew-formula.sh <version> <checksums.txt> > Formula/safegrd.rb
#
# The formula lives in github.com/safegrd/homebrew-tap; the release workflow
# regenerates it after every published tag. It installs the same archives the
# install script does, so both routes deliver the same bytes.
set -eu

version="$1"
sums="$2"
base="https://github.com/safegrd/cli/releases/download/v${version}"

sha() {
  hash="$(awk -v f="safegrd_${version}_$1.tar.gz" '$2 == f || $2 == "*"f {print $1}' "$sums")"
  if [ -z "$hash" ]; then
    echo "homebrew-formula: safegrd_${version}_$1.tar.gz is not in $sums" >&2
    exit 1
  fi
  printf '%s' "$hash"
}

cat <<RUBY
# Generated by scripts/homebrew-formula.sh in github.com/safegrd/cli for v${version}.
# Do not edit by hand: the next release overwrites it.
class Safegrd < Formula
  desc "Encrypted, immutable backups with proof that they restore"
  homepage "https://safegrd.dev"
  version "${version}"
  license "BUSL-1.1"

  on_macos do
    on_arm do
      url "${base}/safegrd_${version}_darwin_arm64.tar.gz"
      sha256 "$(sha darwin_arm64)"
    end
    on_intel do
      url "${base}/safegrd_${version}_darwin_amd64.tar.gz"
      sha256 "$(sha darwin_amd64)"
    end
  end

  on_linux do
    on_arm do
      url "${base}/safegrd_${version}_linux_arm64.tar.gz"
      sha256 "$(sha linux_arm64)"
    end
    on_intel do
      url "${base}/safegrd_${version}_linux_amd64.tar.gz"
      sha256 "$(sha linux_amd64)"
    end
  end

  def install
    bin.install "safegrd"
    generate_completions_from_executable(bin/"safegrd", "completion")
  end

  def caveats
    <<~EOS
      Connect this machine to SafeGrd:
        safegrd login     # prints a URL; open it in a browser on any device
        safegrd enroll
      Or set up a standalone host that contacts no server:
        safegrd init
    EOS
  end

  test do
    assert_match "version #{version}", shell_output("#{bin}/safegrd version")
  end
end
RUBY
